### ISSUE TITLE
Few issues with messenger

### ISSUE THREAD

**Issue by CptDinosaur** [ducfilan/Dark-mode-Franz#1]
- The type message bar is still light
- The settings and writing cog in top left should be white
- The name on right should really be white/grey, blue looks a little awkward.

**Comment by ducfilan** [comment]
These issues come with the new update from Facebook. I will fix today.

**Comment by ducfilan** [comment]
> * The name on right should really be white/grey, blue looks a little awkward.

Where is this? I did not notice about this one.

**Comment by ducfilan** [comment]
@CptDinosaur all issues got fixed.
