### ISSUE TITLE
Slack now supports native dark mode

### ISSUE THREAD

**Issue by ChristianIvicevic** [ducfilan/Dark-mode-Franz#10]
Your custom CSS is no longer necessary, Slack now officially supports Dark Mode: https://slackhq.com/dark-mode-for-slack-desktop

**Comment by ducfilan** [comment]
> Your custom CSS is no longer necessary, Slack now officially supports Dark Mode: https://slackhq.com/dark-mode-for-slack-desktop

So you can ignore the file here.
