### ISSUE TITLE
Can't read sent text if FB Messenger conversation has a theme.

### ISSUE THREAD

**Issue by arpandeol** [ducfilan/Dark-mode-Franz#11]
Can't read sent text if FB Messenger conversation has a theme. Anyway to over-ride the theme and have it the gray like incoming messages.

**Comment by ducfilan** [comment]
Can you provide images?

**Comment by ducfilan** [comment]
Btw, messenger has an update, please get the new version and see
if it got fixed: Great!
else: Could you provide images of the problems?
