### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by JustxMeg** [ducfilan/Dark-mode-Franz#12]
Because of a new update with WhatsApp, the text isn't readable anymore does someone have a fix?

![](https://this-domain.is-a.fail/1yRG9g.png)

**Comment by ChristianIvicevic** [comment]
I just updated the stylesheet with the source from the original creator. Just copy the contents of this gist over your current `darkmode.css`: https://gist.github.com/ChristianIvicevic/7c7fb6baa80bc501b9c99e742011a9ad

**Comment by ducfilan** [comment]
@Christian Ivicevic please make a pull request. Thank you 😍

**Comment by JustxMeg** [comment]
https://there-is-really.nothing-to-see-he.re/NkKc67.png
New issue.
