### ISSUE TITLE
Google Calendar doesn't work 100% of the time

### ISSUE THREAD

**Issue by jandreaucodes** [ducfilan/Dark-mode-Franz#14]
I haven't been able to track down the reason why, but (for me, at least) the Google Calendar darkmode only works some of the time.

If I "reload" that service 5 or 10 times, dark mode will work until a refresh or relaunch of Franz.

I'm hoping others see this too, so it's easier to track down.

**Comment by Julian88Tex** [comment]
@jandreaucodes Yeah I'm definitely getting the same behavior.

**Comment by Julian88Tex** [comment]
Example: https://jmp.sh/LWaOhLu

**Comment by ducfilan** [comment]
This problem is from Franz, I can only interfere the css only. The `darkmode.css` injection from Franz's processing causes the problem.

**Comment by ducfilan** [comment]
I made a fix to Franz's `webview.js` file, now it works properly without any problem so far. Take a look at this: https://github.com/ducfilan/Dark-mode-Franz/tree/master/googlecalendar
