### ISSUE TITLE
Multiple messenger issues

### ISSUE THREAD

**Issue by MohamedElgharbawy** [ducfilan/Dark-mode-Franz#15]
1. The like button has a white background
2. The reply and react icons next to a message are pure black, making them hard to see
3. "You replied to [name]" above a message is pure black, making it hard to see
4. Privacy and support icons are pure black, making them hard to see
5. The sticker and gif selectors are white
6. @ suggestions in group chats are white
7. Reaction picker for messages is white
8. Emoji picker is white
9. The background of sent emojis is a different shade of gray

**Comment by Julian88Tex** [comment]
@MohamedElgharbawy Mind adding images of each of these?

**Comment by MohamedElgharbawy** [comment]
1.
![image](https://user-images.githubusercontent.com/30507689/67437454-b533f180-f5a5-11e9-8033-425a5d32ebbb.png)

2. 
![image](https://user-images.githubusercontent.com/30507689/67437468-bc5aff80-f5a5-11e9-9833-8bd628055ee4.png)

3.
![image](https://user-images.githubusercontent.com/30507689/67437483-c4b33a80-f5a5-11e9-9a4c-9ca1d29be49e.png)
4.
![image](https://user-images.githubusercontent.com/30507689/67437687-4dca7180-f5a6-11e9-98d3-b6fcf2b2837a.png)

5.
![image](https://user-images.githubusercontent.com/30507689/67438015-2f18aa80-f5a7-11e9-9ec9-aa9499a6f685.png)
![image](https://user-images.githubusercontent.com/30507689/67438021-3475f500-f5a7-11e9-9cf2-9cf31f96dc23.png)

**Comment by Julian88Tex** [comment]
@MohamedElgharbawy Thanks!

I suspect the like button won't be doable since I suspect it's an image. The sticker/gif selector I doubt will be doable but maybe. The other 3 I'm pretty sure should be doable.

**Comment by MohamedElgharbawy** [comment]
@Julian88Tex There's a google chrome extension, messenger black by Ryan Mohta, that does not have any of these issues. They are all possible to fix.

**Comment by Julian88Tex** [comment]
@MohamedElgharbawy Good to know mind linking to it? Especially would be helpful to link to the repo if it's open-source.

**Comment by MohamedElgharbawy** [comment]
@Julian88Tex https://chrome.google.com/webstore/detail/messenger-black-scheduled/aakklflhdgofndhdkjgalldlnbgpgbob

You can see the source code using this I believe:
https://www.howtogeek.com/198964/how-to-view-the-source-code-of-a-chrome-extension/

**Comment by Julian88Tex** [comment]
@MohamedElgharbawy thanks!

@ryanmohta any chance you've got a public repo of this app somewhere?

**Comment by ducfilan** [comment]
Thank you @MohamedElgharbawy ! Those issues got fixed.

**Comment by MohamedElgharbawy** [comment]
@ducfilan There's a few bugs left

1. Messages you send now have black text instead of white
![image](https://user-images.githubusercontent.com/30507689/67451957-b16c9300-f5d6-11e9-8b35-f8d4b3e0673a.png)

2. The top and bottom of the gif selector are white (as well as the search bar)
![image](https://user-images.githubusercontent.com/30507689/67451970-bdf0eb80-f5d6-11e9-93c5-bf9e90a1599c.png)

3. The search bar and highlighted tab in the stickers selector is white
![image](https://user-images.githubusercontent.com/30507689/67451993-d19c5200-f5d6-11e9-939f-00ba04c7fb9d.png)

4. The games tab is white
![image](https://user-images.githubusercontent.com/30507689/67452018-e7117c00-f5d6-11e9-9dba-a5a4af4922c0.png)

5. While the like button is sending, it'll have a white background. Once it's sent, it has a proper black one.
Couldn't grab a screenshot, it happens very quickly

6. The like button in change emoji is white (instead of blue)
![image](https://user-images.githubusercontent.com/30507689/67452081-1627ed80-f5d7-11e9-8f0b-99d953ea81b2.png)

**Comment by ducfilan** [comment]
@MohamedElgharbawy @Julian88Tex @JustxMeg @ChristianIvicevic I got an update today, please check.

**Comment by Julian88Tex** [comment]
@ducfilan some nice improvements thanks!
