### ISSUE TITLE
Facebook Messenger - Code blocks are yellow

### ISSUE THREAD

**Issue by mathieuf20** [ducfilan/Dark-mode-Franz#16]
When sending a code snippet (code surrounded with triple back-ticks), it displays light gray text on light yellow background, which makes it nearly impossible to read.

**Comment by mathieuf20** [comment]
After some tests, I've found that adding those 2 lines to darkmode.css fixed the issue

`
body ._3058 ._wu0 ._52mr {
	color: white;
}

body ._wu0 {
	background: #222222;
	border: 1px solid #444444;
}`

It does not seem to break anything.

Since I do not know how you organize your code, I'll let you put it where it needs to be.

**Comment by ducfilan** [comment]
> After some tests, I've found that adding those 2 lines to darkmode.css fixed the issue
> 
> ```css
> body ._3058 ._wu0 ._52mr {
> 	color: white;
> }
> 
> body ._wu0 {
> 	background: #222222;
> 	border: 1px solid #444444;
> }
> ```
> 
> It does not seem to break anything.
> 
> Since I do not know how you organize your code, I'll let you put it where it needs to be.

Thank you @mathieuf20 
I updated a new version for Messenger including your fix.
