### ISSUE TITLE
WhatsApp

### ISSUE THREAD

**Issue by Markdejager** [ducfilan/Dark-mode-Franz#18]
The search around WhatsApp has a white background now, last version doesn't fix that.

**Comment by Julian88Tex** [comment]
@JustxMeg could you provide a screenshot? Thanks!

**Comment by JustxMeg** [comment]
@Julian88Tex sure thing!
![image](https://user-images.githubusercontent.com/7931828/72604766-d776aa80-391b-11ea-9db8-249cef84ecc8.png)
![image](https://user-images.githubusercontent.com/7931828/72604799-e8272080-391b-11ea-8661-f26f9571bcfb.png)
Maybe the text at the arrow can be white too?

**Comment by Julian88Tex** [comment]
@JustxMeg thanks!

**Comment by JustxMeg** [comment]
No worries, wasn’t able to find a fix myself for it.

Van: Julian Joseph <notifications@github.com> 
Verzonden: vrijdag 17 januari 2020 20:20
Aan: ducfilan/Dark-mode-Franz <Dark-mode-Franz@noreply.github.com>
CC: Dropbox <mark@nieuwerkerk.nu>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ducfilan/Dark-mode-Franz] WhatsApp (#18)

 

@JustxMeg <https://github.com/JustxMeg>  thanks!

**Comment by JustxMeg** [comment]
@Julian88Tex any ideas if you can fix this?

**Comment by Julian88Tex** [comment]
@JustxMeg I have done any contributing to repo code yet so honestly not sure, but I imagine it's probably possible. The repo owner @ducfilan has been pretty active at fixing issues when they can so maybe they will soon.

**Comment by JustxMeg** [comment]
Would be nice, it's looks pretty bad. I'm not sure where I can find the search bar.

**Comment by ducfilan** [comment]
@Markdejager I updated the new version. Let's check if it got fixed.

**Comment by Julian88Tex** [comment]
@ducfilan mine actually got much worse after this update

![Screenshot 2020-01-22 00 08 44](https://user-images.githubusercontent.com/459099/72876630-cd520480-3cab-11ea-90d5-97d783bd2bdb.png)
![Screenshot 2020-01-22 00 08 58](https://user-images.githubusercontent.com/459099/72876631-cdea9b00-3cab-11ea-8ad4-4a84b7fe40c7.png)

**Comment by ducfilan** [comment]
Sorry, please try again the latest version.

**Comment by Julian88Tex** [comment]
@ducfilan Thanks that did the trick for the search box:

<img width="410" alt="Screenshot 2020-01-22 00 56 19" src="https://user-images.githubusercontent.com/459099/72879618-20c75100-3cb2-11ea-9b3e-5a3ec49b8025.png">

@Markdejager also noted the "No chats, contacts"/"Loading for chats" text is too dark to read which is still the case:

<img width="391" alt="Screenshot 2020-01-22 00 56 30" src="https://user-images.githubusercontent.com/459099/72879706-481e1e00-3cb2-11ea-97c8-f541e7c021b1.png">
<img width="392" alt="Screenshot 2020-01-22 00 56 24" src="https://user-images.githubusercontent.com/459099/72879707-481e1e00-3cb2-11ea-8708-e35501fd2b7c.png">

**Comment by ducfilan** [comment]
It's a different problem, I will update later. This issue will be closed.
