### ISSUE TITLE
Recommendation for Google Calendar workaround adds a greyscale to everything

### ISSUE THREAD

**Issue by Julian88Tex** [ducfilan/Dark-mode-Franz#19]
After performing javascript workaround in Developer Console as described in [ReadMe for Google Calendar](https://github.com/ducfilan/Dark-mode-Franz/blob/master/googlecalendar/README.md), everything takes on a greyscale.

For example, here is left bar in Fran before:
<img width="59" alt="Screenshot 2020-01-22 00 15 30" src="https://user-images.githubusercontent.com/459099/72877019-c4156780-3cac-11ea-888a-a203fe5d6a5d.png">

After:
<img width="54" alt="Screenshot 2020-01-22 00 14 53" src="https://user-images.githubusercontent.com/459099/72877031-ca0b4880-3cac-11ea-83b8-5fe1022241ba.png">

**Comment by ducfilan** [comment]
You need to paste to open `Toggle Service Developer Tools`, not `Toggle Developer Tools`.

**Comment by Julian88Tex** [comment]
@ducfilan Ah thanks for clarifying! That worked.
