### ISSUE TITLE
Slack dark mode

### ISSUE THREAD

**Issue by jam-time** [ducfilan/Dark-mode-Franz#2]
I adopted the slack dark mode into Franz for myself a few days ago, and it looked great everywhere except in threads. The flex header and input box were both still white with white text. I tried to make some changes to the .css file myself to fix it, but I seem to have broken more than I fixed. Now the main header and input box are white, and all of the thread flexpane is white, even after reverting my changes, and after uninstalling/reinstalling Franz and deleting any files I could find. Not sure if you could help with my problem specifically, but I figured I'd let you know that the thread stuff doesn't seem to work.

**Comment by ducfilan** [comment]
@jam-time I updated slack, these issues come from their new updates. Please check.

**Comment by jam-time** [comment]
Awesome, looks great!
