### ISSUE TITLE
.css files need to be renamed as part of installation

### ISSUE THREAD

**Issue by Julian88Tex** [ducfilan/Dark-mode-Franz#4]
**Issue**
Part of the manual installation is renaming the .css files to correspond with their current names in their folders. For example, in slack it's name `service.css`:

<img width="1031" alt="Screenshot 2019-09-09 13 46 26" src="https://user-images.githubusercontent.com/459099/64565316-532a7000-d308-11e9-9dea-1551b4fabfea.png">

I recommend adding this to the ReadMe.

**Comment by ducfilan** [comment]
There's no need of any replacement. You should do exactly the installation guide.

**Comment by Julian88Tex** [comment]
Ah thanks for clarifying misread.
