### ISSUE TITLE
Some services do not have .css files

### ISSUE THREAD

**Issue by Julian88Tex** [ducfilan/Dark-mode-Franz#5]
**Issue**
It appears some services do not have .css files like Messenger and Google Chat (not currently supported) and therefore not able to be replaced. Perhaps they did in the past or perhaps they are stored somewhere else:

<img width="1031" alt="Screenshot 2019-09-09 13 52 59" src="https://user-images.githubusercontent.com/459099/64565676-26c32380-d309-11e9-8ab1-a50f17b93758.png">

**Comment by ducfilan** [comment]
There's no replacement. The `darkmode.css` and the css file already on the folder are not related to each other.
You can read the [installation](https://github.com/ducfilan/Dark-mode-Franz#installation) guide.

**Comment by Julian88Tex** [comment]
Ah thanks for clarifying misread.
